print(bool(0))   
print(bool(1))
print(bool(-1))

print(bool(0))
print(bool(1.5))
print(bool(-1.5))
print("the new Line")
print(str(True))
print(type(str(True)))
print(str(False))
print(type(str(False)))